/** các múi giờ */
export const TIME_ZONES = [
  "GMT -12:00 Baker Island",
  "GMT -11:00 Niue, Pago Pago",
  "GMT -10:00 Honolulu, Papeete",
  "GMT -9:30 Marquesas Islands",
  "GMT -9:00 Anchorage, Gambier Islands",
  "GMT -8:00 Los Angeles, Vancouver, Tijuana",
  "GMT -7:00 Denver, Phoenix, Edmonton",
  "GMT -6:00 Chicago, Mexico City, Guatemala City",
  "GMT -5:00 New York, Toronto, Lima",
  "GMT -4:00 Santiago, Caracas, La Paz",
  "GMT -3:30 St. John's",
  "GMT -3:00 Buenos Aires, Montevideo, São Paulo",
  "GMT -2:00 South Georgia, South Sandwich Islands",
  "GMT -1:00 Azores, Cape Verde",
  "GMT +0:00 London, Dublin, Lisbon",
  "GMT +1:00 Paris, Berlin, Madrid",
  "GMT +2:00 Cairo, Johannesburg, Athens",
  "GMT +3:00 Moscow, Riyadh, Nairobi",
  "GMT +3:30 Tehran",
  "GMT +4:00 Dubai, Baku, Samara",
  "GMT +4:30 Kabul",
  "GMT +5:00 Karachi, Tashkent, Maldives",
  "GMT +5:30 New Delhi, Colombo",
  "GMT +5:45 Kathmandu",
  "GMT +6:00 Dhaka, Thimphu, Omsk",
  "GMT +6:30 Yangon, Cocos Islands",
  "GMT +7:00 Hanoi, Bangkok, Jakarta",
  "GMT +8:00 Beijing, Singapore, Manila",
  "GMT +8:45 Eucla",
  "GMT +9:00 Tokyo, Seoul, Yakutsk",
  "GMT +9:30 Adelaide, Darwin",
  "GMT +10:00 Sydney, Port Moresby, Vladivostok",
  "GMT +10:30 Lord Howe Island",
  "GMT +11:00 Nouméa, Magadan, Solomon Islands",
  "GMT +12:00 Auckland, Fiji, Kamchatka",
  "GMT +12:45 Chatham Islands",
  "GMT +13:00 Nukuʻalofa, Samoa",
  "GMT +14:00 Kiritimati Island"
]

/** các đơn vị tiền tệ */
export const CURRENCIES: Record<string, string> = {
  VND: 'Việt Nam Đồng',
  JPY: 'Yên Nhật',
  USD: 'Đô la Mỹ',
  EUR: 'Euro',
  GBP: 'Bảng Anh',
  CNY: 'Nhân dân tệ',
  KRW: 'Won Hàn Quốc',
}

/** các quốc gia và mã code aplha-2 */
export const COUNTRIES: Record<string, string> = {
  // Đông Nam Á
  VN: "Việt Nam",
  TH: "Thái Lan",
  MY: "Malaysia",
  SG: "Singapore",
  ID: "Indonesia",
  PH: "Philippines",
  KH: "Campuchia",
  LA: "Lào",
  MM: "Myanmar",
  US: "Hoa Kỳ",
  GB: "Vương quốc Anh",
  JP: "Nhật Bản",
  KR: "Hàn Quốc",
  CN: "Trung Quốc",
  AU: "Úc",
};
